package ex08_Exception;

public class Exceptionex4 {

	public static void main(String[] args) {
		int num1=3, num2 = 0;
		int result = num1/num2;
		System.out.println(result);
	}
}
